# Generated by Django 3.0.7 on 2020-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoopeasy', '0002_auto_20200707_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_email', models.CharField(default='', max_length=80)),
                ('cust_phone', models.CharField(default='', max_length=12)),
                ('cust_desc', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
