# Generated by Django 3.0.7 on 2020-07-17 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoopeasy', '0006_updateorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorder',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 19, 36, 12, 268580)),
        ),
    ]
